version: '2'

jobs:
  lint:
    docker:
      - image: php:alpine
    steps:
      - checkout
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Composer Install
          command: composer install --no-progress --no-interaction
      - run:
          name: Composer Check Style
          command: composer check-style

  test-php80:
    docker:
      - image: php:8.0-alpine
    steps:
      - checkout
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Composer Install
          command: composer install --no-progress --no-interaction
      - run:
          name: Composer Test
          command: composer test

workflows:
  version: 2
  tests:
    jobs:
      - lint
      - test-php80
